# Generated by Django 4.0 on 2021-12-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=30)),
                ('brand', models.CharField(blank=True, max_length=30)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('price', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('product_image', models.ImageField(blank=True, upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timstamp', models.DateTimeField(auto_now=True)),
                ('placed', models.BooleanField(default=False)),
                ('total_price', models.IntegerField()),
                ('total_qty', models.IntegerField()),
                ('product', models.ManyToManyField(blank=True, to='core.Product')),
            ],
        ),
    ]
